                      MuadDib's Dat Format File Made For
                        [ Relativity (c)  Issue #  3 ]
                     -===_____ ___  ===== _____=_____===-
                     .:::\___ |_ \\____ __\___ | ___/:::.
                    .::::://   _\  \\_ '  `_/  :  \\:::::.
                     .:::/   _: __//  _:___//. `\   \:::.
                      .://  |  \\__ .  __>___  /_\ . \:.
                      _/   _\_    _\   .|  \\ .      \\_
                      \_____/\____//.   :_. \\_________/
                     -=========LZ\___________/97========-
                              ' -=============- ' 
                  If u think u can crack this open i'll even
               help u crackers, here is the complex encryption
                   key i made :>>>>>>>>333333333<<<<<<<<<<